# Generated by Django 3.1.5 on 2021-07-30 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New')),
                ('vdgsa_number', models.IntegerField(blank=True, null=True)),
                ('maker', models.CharField(max_length=50, null=True)),
                ('size', models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven_string_bass', 'Seven-String Bass'), ('other', 'Other')], default='bass')),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('provenance', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('accession_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('program', models.TextField(choices=[('Regular', 'Regular'), ('Select Reserve', 'Select Reserve'), ('Consort Loan', 'Consort Loan')], default='Regular')),
                ('bow_num', models.AutoField(primary_key=True, serialize=False)),
                ('storer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New')),
                ('vdgsa_number', models.IntegerField(blank=True, null=True)),
                ('maker', models.CharField(max_length=50, null=True)),
                ('size', models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven_string_bass', 'Seven-String Bass'), ('other', 'Other')], default='bass')),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('provenance', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('accession_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('program', models.TextField(choices=[('Regular', 'Regular'), ('Select Reserve', 'Select Reserve'), ('Consort Loan', 'Consort Loan')], default='Regular')),
                ('case_num', models.AutoField(primary_key=True, serialize=False)),
                ('storer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('vbc_number', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=4)),
                ('orig_image_file_name', models.CharField(max_length=250)),
                ('image_file_name', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('thumb_file_name', models.CharField(blank=True, max_length=250, null=True)),
                ('thumb_width', models.IntegerField(blank=True, null=True)),
                ('thumb_height', models.IntegerField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New')),
                ('entry_num', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/%Y/')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('original_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Viol',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New')),
                ('vdgsa_number', models.IntegerField(blank=True, null=True)),
                ('maker', models.CharField(max_length=50, null=True)),
                ('size', models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven_string_bass', 'Seven-String Bass'), ('other', 'Other')], default='bass')),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('provenance', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('accession_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('program', models.TextField(choices=[('Regular', 'Regular'), ('Select Reserve', 'Select Reserve'), ('Consort Loan', 'Consort Loan')], default='Regular')),
                ('viol_num', models.AutoField(primary_key=True, serialize=False)),
                ('strings', models.PositiveIntegerField(blank=True)),
                ('renter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('storer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New')),
                ('entry_num', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven_string_bass', 'Seven-String Bass'), ('other', 'Other')])),
                ('date_req', models.DateField(blank=True, null=True)),
                ('renter_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viol_num', models.ForeignKey(blank=True, db_column='viol_num', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitingList', to='rental_viols.viol')),
            ],
            options={
                'ordering': ('-entry_num',),
            },
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New')),
                ('entry_num', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.TextField(choices=[('Available', 'Available'), ('Attached', 'Attached'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Retired', 'Retired'), ('Renewed', 'Renewed'), ('Reserved', 'Reserved'), ('Returned', 'Returned')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('rental_start', models.DateField(blank=True, null=True)),
                ('rental_end', models.DateField(blank=True, null=True)),
                ('bow_num', models.ForeignKey(blank=True, db_column='bow_num', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='rental_viols.bow')),
                ('case_num', models.ForeignKey(blank=True, db_column='case_num', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='rental_viols.case')),
                ('contract_scan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental', to='rental_viols.rentalcontract')),
                ('renter_num', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('viol_num', models.ForeignKey(blank=True, db_column='viol_num', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='rental_viols.viol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='viol_num',
            field=models.ForeignKey(blank=True, db_column='viol_num', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='rental_viols.viol'),
        ),
        migrations.AddField(
            model_name='bow',
            name='viol_num',
            field=models.ForeignKey(blank=True, db_column='viol_num', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bows', to='rental_viols.viol'),
        ),
    ]
