# Generated by Django 3.1.5 on 2021-01-22 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('bow_num', models.AutoField(primary_key=True, serialize=False)),
                ('vdgsa_number', models.IntegerField(blank=True, null=True)),
                ('maker', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=9, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('provenance', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('accession_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('storer', models.IntegerField(blank=True, null=True)),
                ('program', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_num', models.AutoField(primary_key=True, serialize=False)),
                ('vdgsa_number', models.IntegerField(blank=True, null=True)),
                ('maker', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=9, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('provenance', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('accession_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('storer', models.IntegerField(blank=True, null=True)),
                ('program', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('vbc_number', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=4)),
                ('orig_image_file_name', models.CharField(max_length=250)),
                ('image_file_name', models.CharField(max_length=250)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('thumb_file_name', models.CharField(max_length=250)),
                ('thumb_width', models.IntegerField()),
                ('thumb_height', models.IntegerField()),
                ('caption', models.CharField(max_length=3000)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('entry_num', models.AutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=30)),
                ('digest', models.CharField(max_length=64)),
                ('active', models.IntegerField()),
                ('may_edit', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('prog_num', models.AutoField(primary_key=True, serialize=False)),
                ('prog_name', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('renter_num', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('stateprov', models.CharField(blank=True, max_length=2, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('phone_day', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_eve', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_cell', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScanFiles',
            fields=[
                ('entry_num', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('original_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Storer',
            fields=[
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('stateprov', models.CharField(blank=True, max_length=2, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('phone_day', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_eve', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_cell', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('storer_num', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Viol',
            fields=[
                ('viol_num', models.AutoField(primary_key=True, serialize=False)),
                ('vdgsa_number', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=17, null=True)),
                ('strings', models.PositiveIntegerField(blank=True, null=True)),
                ('maker', models.CharField(blank=True, max_length=50, null=True)),
                ('inst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('provenance', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('accession_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=9, null=True)),
                ('program', models.ForeignKey(db_column='program', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.program')),
                ('renter', models.ForeignKey(db_column='renter', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.renter')),
                ('storer', models.ForeignKey(db_column='storer', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.storer')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('entry_num', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, max_length=17, null=True)),
                ('date_req', models.DateField(blank=True, null=True)),
                ('renter_num', models.ForeignKey(db_column='renter_num', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.renter')),
                ('viol_num', models.ForeignKey(db_column='viol_num', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.viol')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('entry_num', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rental_start', models.DateField(blank=True, null=True)),
                ('rental_end', models.DateField(blank=True, null=True)),
                ('contract_scan', models.IntegerField(blank=True, null=True)),
                ('bow_num', models.ForeignKey(db_column='bow_num', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.bow')),
                ('case_num', models.ForeignKey(db_column='case_num', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.case')),
                ('renter_num', models.ForeignKey(db_column='renter_num', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.renter')),
                ('viol_num', models.ForeignKey(db_column='viol_num', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.viol')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='viol_num',
            field=models.ForeignKey(db_column='viol_num', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.viol'),
        ),
        migrations.AddField(
            model_name='bow',
            name='viol_num',
            field=models.ForeignKey(db_column='viol_num', on_delete=django.db.models.deletion.PROTECT, to='rental_viols.viol'),
        ),
    ]
