# Generated by Django 3.1.5 on 2021-01-23 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bow',
            name='viol_num',
            field=models.ForeignKey(blank=True, db_column='viol_num', null=True, on_delete=django.db.models.deletion.PROTECT, to='rental_viols.viol'),
        ),
        migrations.AlterField(
            model_name='case',
            name='viol_num',
            field=models.ForeignKey(blank=True, db_column='viol_num', null=True, on_delete=django.db.models.deletion.PROTECT, to='rental_viols.viol'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='bow_num',
            field=models.ForeignKey(blank=True, db_column='bow_num', null=True, on_delete=django.db.models.deletion.PROTECT, to='rental_viols.bow'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='case_num',
            field=models.ForeignKey(blank=True, db_column='case_num', null=True, on_delete=django.db.models.deletion.PROTECT, to='rental_viols.case'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='viol_num',
            field=models.ForeignKey(blank=True, db_column='viol_num', null=True, on_delete=django.db.models.deletion.PROTECT, to='rental_viols.viol'),
        ),
        migrations.AlterField(
            model_name='viol',
            name='program',
            field=models.ForeignKey(blank=True, db_column='program', null=True, on_delete=django.db.models.deletion.PROTECT, to='rental_viols.program'),
        ),
        migrations.AlterField(
            model_name='viol',
            name='renter',
            field=models.ForeignKey(blank=True, db_column='renter', null=True, on_delete=django.db.models.deletion.PROTECT, to='rental_viols.renter'),
        ),
        migrations.AlterField(
            model_name='viol',
            name='storer',
            field=models.ForeignKey(blank=True, db_column='storer', null=True, on_delete=django.db.models.deletion.PROTECT, to='rental_viols.storer'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='viol_num',
            field=models.ForeignKey(blank=True, db_column='viol_num', null=True, on_delete=django.db.models.deletion.PROTECT, to='rental_viols.viol'),
        ),
    ]
