# Generated by Django 3.1.5 on 2021-10-11 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_viols', '0002_auto_20211011_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='renter_num',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
