# Generated by Django 3.1.5 on 2021-10-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0003_auto_20211011_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='size',
            field=models.TextField(blank=True, choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven_string_bass', 'Seven-String Bass'), ('other', 'Other')], null=True),
        ),
    ]
