# Generated by Django 3.1.4 on 2021-01-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0004_auto_20210123_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bow',
            name='program',
            field=models.TextField(blank=True, choices=[('regular', 'Regular'), ('select_reserve', 'Select Reserve'), ('consort_loan', 'Consort Loan')], default='regular'),
        ),
    ]
