# Generated by Django 3.1.4 on 2021-01-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0005_auto_20210123_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('rental_manager', 'Rental Manager'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='bow',
            name='program',
            field=models.TextField(choices=[('regular', 'Regular'), ('select_reserve', 'Select Reserve'), ('consort_loan', 'Consort Loan')], default='regular'),
        ),
    ]
