# Generated by Django 3.1.7 on 2021-11-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0006_waitinglist_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bow',
            name='size',
            field=models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven-string bass', 'Seven-String Bass'), ('other', 'Other')], default='bass'),
        ),
        migrations.AlterField(
            model_name='bow',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached'), ('Unknown', 'Unknown')], default='New'),
        ),
        migrations.AlterField(
            model_name='case',
            name='size',
            field=models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven-string bass', 'Seven-String Bass'), ('other', 'Other')], default='bass'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached'), ('Unknown', 'Unknown')], default='New'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached'), ('Unknown', 'Unknown')], default='New'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached'), ('Unknown', 'Unknown')], default='New'),
        ),
        migrations.AlterField(
            model_name='viol',
            name='size',
            field=models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven-string bass', 'Seven-String Bass'), ('other', 'Other')], default='bass'),
        ),
        migrations.AlterField(
            model_name='viol',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached'), ('Unknown', 'Unknown')], default='New'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='size',
            field=models.TextField(blank=True, choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven-string bass', 'Seven-String Bass'), ('other', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached'), ('Unknown', 'Unknown')], default='New'),
        ),
    ]
