# Generated by Django 3.2.13 on 2023-01-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0007_auto_20211113_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bow',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached'), ('Unknown', 'Unknown')], default='Unattached'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached'), ('Unknown', 'Unknown')], default='Unattached'),
        ),
    ]
