# Generated by Django 3.1.4 on 2021-01-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0007_auto_20210123_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='viol_num',
            field=models.ForeignKey(blank=True, db_column='viol_num', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='rental_viols.viol'),
        ),
    ]
