# Generated by Django 3.1.5 on 2021-01-23 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_viols', '0008_auto_20210123_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accession_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='maker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='program',
            field=models.TextField(choices=[('regular', 'Regular'), ('select_reserve', 'Select Reserve'), ('consort_loan', 'Consort Loan')], default='regular'),
        ),
        migrations.AddField(
            model_name='case',
            name='provenance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='size',
            field=models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven_string_bass', 'Seven-String Bass'), ('other', 'Other')], default='bass'),
        ),
        migrations.AddField(
            model_name='case',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='storer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='vdgsa_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='accession_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='maker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='size',
            field=models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven_string_bass', 'Seven-String Bass'), ('other', 'Other')], default='bass'),
        ),
        migrations.AlterField(
            model_name='bow',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='vdgsa_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viol',
            name='accession_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viol',
            name='maker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='viol',
            name='size',
            field=models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven_string_bass', 'Seven-String Bass'), ('other', 'Other')], default='bass'),
        ),
        migrations.AlterField(
            model_name='viol',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='viol',
            name='vdgsa_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
