# Generated by Django 3.1.5 on 2021-01-29 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0009_auto_20210123_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='bow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bow',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bow',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active'),
        ),
        migrations.AddField(
            model_name='viol',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viol',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viol',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active'),
        ),
    ]
