# Generated by Django 3.1.5 on 2021-01-30 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0010_auto_20210129_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'ordering': ('-entry_num',)},
        ),
        migrations.RemoveField(
            model_name='rentalhistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='viol',
            name='inst_value',
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='event',
            field=models.TextField(choices=[('attached', 'Attached'), ('detached', 'Detached'), ('reserved_for', 'Reserved'), ('rented', 'Rented'), ('retired', 'Retired'), ('returned', 'Returned')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
