# Generated by Django 3.1.5 on 2021-02-01 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0012_auto_20210131_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='bow_num',
            field=models.ForeignKey(blank=True, db_column='bow_num', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='rental_viols.bow'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='case_num',
            field=models.ForeignKey(blank=True, db_column='case_num', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='rental_viols.case'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='viol_num',
            field=models.ForeignKey(blank=True, db_column='viol_num', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='rental_viols.viol'),
        ),
    ]
