# Generated by Django 3.1.6 on 2021-02-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0013_auto_20210201_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bow',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('attached', 'Attached'), ('deleted', 'Deleted'), ('detached', 'Detached'), ('reserved_for', 'Reserved'), ('rented', 'Rented'), ('retired', 'Retired'), ('returned', 'Returned')], default='active'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('attached', 'Attached'), ('deleted', 'Deleted'), ('detached', 'Detached'), ('reserved_for', 'Reserved'), ('rented', 'Rented'), ('retired', 'Retired'), ('returned', 'Returned')], default='active'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='event',
            field=models.TextField(choices=[('active', 'Active'), ('attached', 'Attached'), ('deleted', 'Deleted'), ('detached', 'Detached'), ('reserved_for', 'Reserved'), ('rented', 'Rented'), ('retired', 'Retired'), ('returned', 'Returned')]),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('attached', 'Attached'), ('deleted', 'Deleted'), ('detached', 'Detached'), ('reserved_for', 'Reserved'), ('rented', 'Rented'), ('retired', 'Retired'), ('returned', 'Returned')], default='active'),
        ),
        migrations.AlterField(
            model_name='viol',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('attached', 'Attached'), ('deleted', 'Deleted'), ('detached', 'Detached'), ('reserved_for', 'Reserved'), ('rented', 'Rented'), ('retired', 'Retired'), ('returned', 'Returned')], default='active'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('attached', 'Attached'), ('deleted', 'Deleted'), ('detached', 'Detached'), ('reserved_for', 'Reserved'), ('rented', 'Rented'), ('retired', 'Retired'), ('returned', 'Returned')], default='active'),
        ),
    ]
