# Generated by Django 3.1.5 on 2021-02-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0015_auto_20210212_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contracts/%Y/'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='size',
            field=models.TextField(choices=[('pardessus', 'Pardessus'), ('treble', 'Treble'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass'), ('seven_string_bass', 'Seven-String Bass'), ('other', 'Other')]),
        ),
    ]
