# Generated by Django 3.1.5 on 2021-03-03 01:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0016_auto_20210226_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('attached', 'Attached'), ('deleted', 'Deleted'), ('detached', 'Detached'), ('new', 'New'), ('reserved_for', 'Reserved'), ('rented', 'Rented'), ('retired', 'Retired'), ('returned', 'Returned')], default='new'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='contract_scan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='rental_viols.rentalcontract'),
        ),
    ]
