# Generated by Django 3.1.5 on 2021-03-03 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0017_auto_20210303_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='contract_scan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental', to='rental_viols.rentalcontract'),
        ),
    ]
