# Generated by Django 3.1.6 on 2021-03-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0018_auto_20210303_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='viol_num',
            field=models.ForeignKey(blank=True, db_column='viol_num', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitingList', to='rental_viols.viol'),
        ),
    ]
