# Generated by Django 3.1.5 on 2021-04-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0019_auto_20210323_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file_name',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
