# Generated by Django 3.1.5 on 2021-07-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0021_auto_20210406_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bow',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='event',
            field=models.TextField(choices=[('Available', 'Available'), ('Deleted', 'Deleted'), ('New', 'New'), ('Rented', 'Rented'), ('Retired', 'Retired'), ('Renewed', 'Renewed'), ('Returned', 'Returned')]),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New'),
        ),
        migrations.AlterField(
            model_name='viol',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='status',
            field=models.TextField(choices=[('Attached', 'Attached'), ('Available', 'Available'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Reserved', 'Reserved'), ('Retired', 'Retired'), ('Unattached', 'Unattached')], default='New'),
        ),
    ]
