# Generated by Django 3.1.5 on 2021-07-13 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_viols', '0022_auto_20210710_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='event',
            field=models.TextField(choices=[('Available', 'Available'), ('Attached', 'Attached'), ('Deleted', 'Deleted'), ('Detached', 'Detached'), ('New', 'New'), ('Rented', 'Rented'), ('Retired', 'Retired'), ('Renewed', 'Renewed'), ('Reserved', 'Reserved'), ('Returned', 'Returned')]),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='renter_num',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
