# Generated by Django 3.1.5 on 2021-10-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='address_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='address_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='phone1',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
