# Generated by Django 3.1.5 on 2021-11-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_viols', '0005_auto_20211018_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
