FROM python:3.10

ARG DEPLOYMENT_MODE

WORKDIR /usr/src/app

RUN pip install uwsgi
RUN pip install pipenv

COPY ./Pipfile .
COPY ./Pipfile.lock .
RUN pipenv install --system

COPY . /usr/src/app

RUN ./manage.py collectstatic --noinput
