# Generated by Django 3.1.7 on 2021-04-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0001_squashed_0008_auto_20210428_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular Curriculum (part- and full-time)'), ('beginners', 'Beginner Programs (both teen and adult)'), ('consort_coop', 'Consort Cooperative'), ('seasoned_players', 'Seasoned Players'), ('advanced_projects', 'Advanced Projects'), ('faculty_guest_other', 'Faculty/Guest/Other')], max_length=50),
        ),
    ]
