# Generated by Django 3.1.7 on 2021-04-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0001_squashed_0010_auto_20210422_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularprogramclasschoices',
            name='tuition_option',
        ),
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular'), ('faculty_guest_other', 'Faculty/Guest/Other'), ('beginners', 'Beginners'), ('consort_coop', 'Consort Cooperative'), ('seasoned_players', 'Seasoned Players'), ('exhibitor', 'Vendor')], max_length=50),
        ),
    ]
