# Generated by Django 3.1.7 on 2021-04-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0003_auto_20210427_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='donation',
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='first_period_time_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='fourth_period_time_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='photo_release_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='second_period_time_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='third_period_time_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tshirts',
            name='donation',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='basicregistrationinfo',
            name='buddy_willingness',
            field=models.TextField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')]),
        ),
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular Curriculum (part- and full-time)'), ('beginners', 'Beginner Programs (both teen and adult)'), ('consort_coop', 'Consort Cooperative'), ('seasoned_players', 'Seasoned Players'), ('advanced_projects', 'Advanced Projects'), ('faculty_guest_other', 'Faculty/Guest/Other')], max_length=50),
        ),
    ]
