# Generated by Django 3.1.7 on 2021-04-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0005_auto_20210430_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(max_length=255),
        ),
    ]
