# Generated by Django 3.1.7 on 2021-04-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0006_auto_20210430_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.CharField(max_length=255),
        ),
    ]
