# Generated by Django 3.1.7 on 2021-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0007_auto_20210430_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
