# Generated by Django 3.1.7 on 2021-05-07 12:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0008_auto_20210430_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicregistrationinfo',
            old_name='is_first_time_attendee',
            new_name='attended_nonclave',
        ),
        migrations.AddField(
            model_name='basicregistrationinfo',
            name='archival_video_release',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='archival_video_release_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular Curriculum (part- and full-time)'), ('beginners', 'Introduction to the Viol (free)'), ('teen_beginners', 'Teen Beginners (free)'), ('consort_coop', 'Consort Cooperative'), ('seasoned_players', 'Seasoned Players'), ('advanced_projects', 'Advanced Projects'), ('faculty_guest_other', 'Faculty/Guest/Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirts',
            name='tshirt1',
            field=models.CharField(blank=True, choices=[("Men's S", "Men's S"), ("Men's M", "Men's M"), ("Men's L", "Men's L"), ("Men's XL", "Men's XL"), ("Men's XXL", "Men's XXL"), ("Men's XXXL", "Men's XXXL"), ("Women's Fitted S", "Women's Fitted S"), ("Women's Fitted M", "Women's Fitted M"), ("Women's Fitted L", "Women's Fitted L"), ("Women's V-neck S", "Women's V-neck S"), ("Women's V-neck M", "Women's V-neck M"), ("Women's V-neck L", "Women's V-neck L"), ("Women's V-neck XL", "Women's V-neck XL")], max_length=50),
        ),
        migrations.AlterField(
            model_name='tshirts',
            name='tshirt2',
            field=models.CharField(blank=True, choices=[("Men's S", "Men's S"), ("Men's M", "Men's M"), ("Men's L", "Men's L"), ("Men's XL", "Men's XL"), ("Men's XXL", "Men's XXL"), ("Men's XXXL", "Men's XXXL"), ("Women's Fitted S", "Women's Fitted S"), ("Women's Fitted M", "Women's Fitted M"), ("Women's Fitted L", "Women's Fitted L"), ("Women's V-neck S", "Women's V-neck S"), ("Women's V-neck M", "Women's V-neck M"), ("Women's V-neck L", "Women's V-neck L"), ("Women's V-neck XL", "Women's V-neck XL")], max_length=50),
        ),
        migrations.AlterField(
            model_name='workstudyapplication',
            name='job_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('google_drive_file_organizing', 'Collecting and organizing files on DropBox and Google Drive (before Conclave)'), ('video_editing', 'Video editing (before Conclave)'), ('assist_music_director_before_conclave', 'Assisting the music director (before Conclave)'), ('auction_prep_before_conclave', 'Auction preparation: collecting photos, writing descriptions of items (mostly in the few days before Conclave)'), ('auction_prep_during_conclave', 'Auction preparation: collecting photos, writing descriptions of items (mostly Sun-Tues during Conclave)'), ('social_event_helper', 'Social event helpers (specific times, e.g. lunchtime, ice cream social, Conclave banquet)'), ('tech_support', 'Answering tech-support type questions, like Zoom help, accessing YouTube, downloading files, etc. (specific shifts during Conclave)'), ('auction_event_helper', 'Auction event helpers (during the Conclave auction)'), ('assist_music_director_during_conclave', 'Assisting the music director (during Conclave)')], max_length=100), size=None),
        ),
        migrations.CreateModel(
            name='BeginnerInstrumentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_instrument', models.TextField(choices=[('yes', 'Yes'), ('no', 'No')])),
                ('instrument_bringing', models.TextField(blank=True, choices=[('treble', 'Treble'), ('tenor', 'Tenor'), ('bass', 'Bass')])),
                ('registration_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beginner_instrument_info', to='conclave_registration.registrationentry')),
            ],
        ),
    ]
