# Generated by Django 3.1.7 on 2021-05-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0009_auto_20210507_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginnerinstrumentinfo',
            name='registration_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beginner_instruments', to='conclave_registration.registrationentry'),
        ),
    ]
