# Generated by Django 3.1.7 on 2021-06-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0010_auto_20210507_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular Curriculum (part- and full-time)'), ('beginners', 'Introduction to the Viol (free)'), ('teen_beginners', 'Teen Beginners (free)'), ('consort_coop', 'Consort Cooperative'), ('seasoned_players', 'Seasoned Players'), ('advanced_projects', 'Advanced Projects'), ('faculty_guest_other', 'Faculty')], max_length=50),
        ),
    ]
