# Generated by Django 3.1.7 on 2021-10-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0013_instrumentbringing_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicRegistrationInfo',
            new_name='AdditionalRegistrationInfo',
        ),
        migrations.AlterField(
            model_name='instrumentbringing',
            name='purpose',
            field=models.CharField(choices=[('wants_to_borrow', 'I need to borrow this instrument'), ('willing_to_loan', "I'm willing to loan this instrument to someone else"), ('bringing_for_self', "I'm bringing this instrument for myself")], max_length=100),
        ),
    ]
