# Generated by Django 3.1.7 on 2021-10-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0014_auto_20211013_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
