# Generated by Django 3.1.7 on 2021-10-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0016_auto_20211013_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalregistrationinfo',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
