# Generated by Django 3.2.9 on 2021-12-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0019_additionalregistrationinfo_include_in_whos_coming_to_conclave_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularprogramclasschoices',
            name='flex_choice1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conclave_registration.class'),
        ),
        migrations.AddField(
            model_name='regularprogramclasschoices',
            name='flex_choice1_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conclave_registration.instrumentbringing'),
        ),
        migrations.AddField(
            model_name='regularprogramclasschoices',
            name='flex_choice2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conclave_registration.class'),
        ),
        migrations.AddField(
            model_name='regularprogramclasschoices',
            name='flex_choice2_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conclave_registration.instrumentbringing'),
        ),
        migrations.AddField(
            model_name='regularprogramclasschoices',
            name='flex_choice3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conclave_registration.class'),
        ),
        migrations.AddField(
            model_name='regularprogramclasschoices',
            name='flex_choice3_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conclave_registration.instrumentbringing'),
        ),
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular Curriculum'), ('part_time', 'Part-Time Curriculum (1 class + optional freebie)'), ('beginners', 'Introduction to the Viol (free)'), ('teen_beginners', 'Teen Beginners (free)'), ('consort_coop', 'Consort Cooperative'), ('seasoned_players', 'Seasoned Players'), ('advanced_projects', 'Advanced Projects'), ('faculty_guest_other', 'Faculty')], max_length=50),
        ),
    ]
