# Generated by Django 3.2.9 on 2022-01-13 19:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0021_extra_beginners_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular Curriculum'), ('part_time', 'Part-Time Curriculum (1 class + optional freebie)'), ('beginners', 'Introduction to the Viol (free)'), ('consort_coop', 'Consort Cooperative'), ('seasoned_players', 'Seasoned Players/Advanced Projects'), ('advanced_projects', 'Advanced Projects'), ('faculty_guest_other', 'Faculty')], max_length=50),
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.TextField(choices=[('single', 'Single'), ('double', 'Double'), ('off_campus', 'Off Campus')])),
                ('roommate_request', models.TextField(blank=True)),
                ('share_suite_request', models.TextField(blank=True)),
                ('room_near_person_request', models.TextField(blank=True)),
                ('normal_bed_time', models.TextField(choices=[('early', 'Early to bed (11pm)'), ('late', 'Late night (could be 2am!)'), ('no_preference', 'No Preference')])),
                ('arrival_day', models.TextField()),
                ('departure_day', models.TextField()),
                ('is_bringing_child', models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], default='no')),
                ('contact_others_bringing_children', models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], default='no')),
                ('wants_housing_subsidy', models.BooleanField(default=False)),
                ('wants_canadian_currency_exchange_discount', models.BooleanField(default=False)),
                ('dietary_needs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('dairy_free', 'Dairy Free'), ('gluten_free', 'Gluten Free'), ('nut_allergy', 'Nut Allergy'), ('shellfish_allergy', 'Shellfish Allergy')], max_length=50), size=None)),
                ('other_dietary_needs', models.TextField(blank=True)),
                ('banquet_food_choice', models.TextField(choices=[('beef', 'Beef'), ('salmon', 'Salmon'), ('vegan', 'Vegan'), ('not_attending', 'Not Attending')])),
                ('is_bringing_guest_to_banquet', models.BooleanField(default=False)),
                ('banquet_guest_name', models.TextField(blank=True)),
                ('banquet_guest_food_choice', models.TextField(blank=True, choices=[('beef', 'Beef'), ('salmon', 'Salmon'), ('vegan', 'Vegan'), ('not_attending', 'Not Attending')])),
                ('registration_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='conclave_registration.registrationentry')),
            ],
        ),
    ]
