# Generated by Django 3.2.9 on 2022-01-14 16:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0025_workstudyapplication_wants_work_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstudyapplication',
            name='job_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('google_drive_file_organizing', 'Collecting and organizing files on DropBox and Google Drive (before Conclave)'), ('video_editing', 'Video editing (before Conclave)'), ('assist_music_director_before_conclave', 'Assisting the music director (before Conclave)'), ('auction_prep_before_conclave', 'Auction preparation: collecting photos, writing descriptions of items (mostly in the few days before Conclave)'), ('auction_prep_during_conclave', 'Auction preparation: collecting photos, writing descriptions of items (mostly Sun-Tues during Conclave)'), ('social_event_helper', 'Social event helpers (specific times, e.g. lunchtime, ice cream social, Conclave banquet)'), ('tech_support', 'Answering tech-support type questions, like Zoom help, accessing YouTube, downloading files, etc. (specific shifts during Conclave)'), ('auction_event_helper', 'Auction event helpers (during the Conclave auction)'), ('assist_music_director_during_conclave', 'Assisting the music director (during Conclave)')], max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='workstudyapplication',
            name='wants_work_study',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], default=''),
        ),
    ]
