# Generated by Django 3.2.9 on 2022-01-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0026_auto_20220114_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='arrival_date_options',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='departure_date_options',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='housing_form_pre_arrival_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='housing_form_top_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular Curriculum'), ('part_time', 'Part-Time Curriculum (1 class + optional freebie)'), ('beginners', 'Introduction to the Viol (free)'), ('consort_coop', 'Consort Cooperative'), ('seasoned_players', 'Seasoned Players/Advanced Projects'), ('faculty_guest_other', 'Faculty'), ('non_playing_attendee', 'Non-Playing Attendee')], max_length=50),
        ),
    ]
