# Generated by Django 3.2.11 on 2022-01-14 17:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0027_housing_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='arrival_day',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='housing',
            name='departure_day',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='housing',
            name='dietary_needs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('dairy_free', 'Dairy Free'), ('gluten_free', 'Gluten Free'), ('nut_allergy', 'Nut Allergy'), ('shellfish_allergy', 'Shellfish Allergy')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
