# Generated by Django 3.2.11 on 2022-02-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0028_auto_20220114_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='banquet_guest_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='consort_coop_one_extra_class_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='consort_coop_tuition',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='consort_coop_two_extra_classes_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='double_room_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='intro_to_viol_extra_class_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='late_registration_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='non_playing_attendee_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='part_time_tuition',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='regular_tuition',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='seasoned_players_tuition',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='single_room_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='tshirt_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='instrumentbringing',
            name='purpose',
            field=models.CharField(choices=[('bringing_for_self', "I'm bringing this instrument for myself"), ('willing_to_loan', "I'm willing to loan this instrument to someone else"), ('wants_to_borrow', 'I need to borrow this instrument')], max_length=100),
        ),
    ]
