# Generated by Django 3.2.11 on 2022-02-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0030_auto_20220228_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclaveregistrationconfig',
            name='tshirt_price',
            field=models.IntegerField(blank=True, default=25),
        ),
    ]
