# Generated by Django 3.2.11 on 2022-03-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0033_conclaveregistrationconfig_seasoned_players_extra_class_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='work_study_scholarship_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
