# Generated by Django 3.2.11 on 2022-03-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0035_auto_20220302_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginnerinstrumentinfo',
            name='instrument_bringing',
            field=models.TextField(blank=True, choices=[('treble', 'Treble'), ('tenor', 'Tenor'), ('bass', '6-string Bass'), ('7-string Bass', 'Bass 7 String')]),
        ),
        migrations.AlterField(
            model_name='instrumentbringing',
            name='size',
            field=models.CharField(choices=[('treble', 'Treble'), ('tenor', 'Tenor'), ('bass', '6-string Bass'), ('7-string Bass', 'Bass 7 String'), ('other', 'Other Instrument or Rennaissance Viol')], max_length=100),
        ),
    ]
