# Generated by Django 3.2.11 on 2022-03-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0036_auto_20220307_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginnerinstrumentinfo',
            name='instrument_bringing',
            field=models.TextField(blank=True, choices=[('treble', 'Treble'), ('tenor', 'Tenor'), ('bass', '6-string Bass'), ('bass_7_string', '7-string Bass')]),
        ),
        migrations.AlterField(
            model_name='instrumentbringing',
            name='size',
            field=models.CharField(choices=[('treble', 'Treble'), ('tenor', 'Tenor'), ('bass', '6-string Bass'), ('bass_7_string', '7-string Bass'), ('other', 'Other Instrument or Rennaissance Viol')], max_length=100),
        ),
    ]
