# Generated by Django 3.2.11 on 2022-03-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0037_auto_20220309_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='liability_release',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='liability_release_text',
            field=models.TextField(blank=True),
        ),
    ]
