# Generated by Django 3.2.11 on 2022-03-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0041_class_offer_to_beginners'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='age',
            field=models.TextField(choices=[('18-35', '18-35'), ('36-64', '36-64'), ('65+', '65+'), ('Under 18', 'Under 18 (Parent or Guardian must also register)')], default=''),
            preserve_default=False,
        ),
    ]
