# Generated by Django 3.2.11 on 2022-03-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0043_auto_20220328_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='contact_others_bringing_children',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='is_bringing_child',
        ),
    ]
