# Generated by Django 3.2.11 on 2022-03-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0044_auto_20220328_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='banquet_food_options',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='housing',
            name='banquet_food_choice',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='housing',
            name='banquet_guest_food_choice',
            field=models.TextField(blank=True),
        ),
    ]
