# Generated by Django 3.2.11 on 2022-03-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0051_workstudyapplication_can_stay_until_sunday_afternoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstudyapplication',
            name='other_travel_info',
            field=models.TextField(blank=True),
        ),
    ]
