# Generated by Django 3.2.11 on 2022-03-28 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0052_workstudyapplication_other_travel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstudyapplication',
            name='other_jobs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workstudyapplication',
            name='job_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('auction_prep', 'Auction preparation: organize items; write descriptions; keep records'), ('social_event_setup', 'Set up social events; serve refreshments'), ('assist_music_director', 'Assist the music director and/or Conclave coordinators (may include computer-based help and/or fetch-and-carry type tasks)'), ('classroom_setup', 'Set up classrooms (includes moving furniture)'), ('stage_crew', 'Stage crew / stage management during concerts'), ('copy_crew', 'Copy crew: Make and organize photocopies of music for teachers'), ('rental_viols', 'Assist with rental viols (includes organization and also light lifting/carrying instruments)'), ('vdgsa_store', 'Run VdGSA store (no cash involved, but must be responsible & organized)'), ('sign_crew', 'Sign crew: create, print, and hang signs and posters as needed'), ('run_errands', 'Run errands (around campus and/or off campus)')], max_length=100), default=list, size=None),
        ),
    ]
