# Generated by Django 3.2.11 on 2022-03-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0053_auto_20220328_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstudyapplication',
            name='has_car',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], default='no'),
            preserve_default=False,
        ),
    ]
