# Generated by Django 3.2.11 on 2022-03-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0059_auto_20220328_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='covid_policy_markdown',
            field=models.TextField(blank=True),
        ),
    ]
