# Generated by Django 3.2.11 on 2022-04-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0063_auto_20220417_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conclaveregistrationconfig',
            old_name='double_room_cost',
            new_name='double_room_full_week_cost',
        ),
        migrations.RenameField(
            model_name='conclaveregistrationconfig',
            old_name='single_room_cost',
            new_name='single_room_full_week_cost',
        ),
    ]
