# Generated by Django 3.2.11 on 2022-04-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0068_conclaveregistrationconfig_vendor_table_per_day_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conclaveregistrationconfig',
            old_name='vendor_table_per_day_cost',
            new_name='vendor_table_cost_per_day',
        ),
    ]
