# Generated by Django 3.2.11 on 2022-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0069_rename_vendor_table_per_day_cost_conclaveregistrationconfig_vendor_table_cost_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalregistrationinfo',
            name='num_display_space_days',
            field=models.IntegerField(default=6),
        ),
    ]
