# Generated by Django 3.2.11 on 2022-04-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0070_alter_additionalregistrationinfo_num_display_space_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstudyapplication',
            name='nickname',
        ),
    ]
