# Generated by Django 3.2.11 on 2022-04-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0071_remove_workstudyapplication_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
