# Generated by Django 3.2.11 on 2023-04-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0077_auto_20230406_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conclaveregistrationconfig',
            old_name='trust_discount_markdown',
            new_name='discount_markdown',
        ),
    ]
