# Generated by Django 3.2.19 on 2024-02-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0087_auto_20240227_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='room_type',
            field=models.TextField(choices=[('single', 'Single'), ('double', 'Double'), ('off_campus', 'Off Campus')], default=''),
        ),
    ]
