# Generated by Django 3.2.19 on 2025-01-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0089_conclaveregistrationconfig_prorated_workshop_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='overall_level_question_markdown',
            field=models.TextField(blank=True),
        ),
    ]
