# Generated by Django 3.2.19 on 2025-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0091_self_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_freebie',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
