# Generated by Django 3.2.25 on 2025-02-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0091_self_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='can_drive_loaners',
            field=models.TextField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')]),
        ),
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='do_not_send_text_updates',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
