"""
Instructions:

Run this by piping it to a Django shell
in the django container of the running stack.
We recommend redirecting the output to a file to look over.
```
docker exec -it $django_container python3 manage.py shell < clean_country_codes.py &> output
```

This script *should* be idempotent, so if we need to
add new entries we should be able to rerun it.
"""
from django.db import transaction
from vdgsa_backend.accounts.models import User


# Called at the bottom of the file in a transaction
def clean_countries():
    print('Checking', User.objects.count(), 'users')
    for user in User.objects.all():
        change_from = (user.address_country, user.address_state)
        change_to = COUNTRY_STATE_MAPPING.get(change_from)
        if change_to is not None:
            print('Changing', change_from, 'to', change_to, 'for', user)
            user.address_country, user.address_state = change_to

        user.save()


# This mapping was created based on the members database on 2025-12-29
# It was created by a series of rules and adhoc fixes in a jupyter notebook.
COUNTRY_STATE_MAPPING = {
    # Change from: Change to
    ('Argentina', ''): ('Argentina', ''),
     ('Au', 'TAS'): ('Australia', 'TAS'),
     ('Australia', 'NSW'): ('Australia', 'NSW'),
     ('Australia', 'QLD'): ('Australia', 'QLD'),
     ('Australia', 'TAS'): ('Australia', 'TAS'),
     ('Australia', 'VIC'): ('Australia', 'VIC'),
     ('Australia', 'WA'): ('Australia', 'WA'),
     ('Australia', ''): ('Australia', ''),
     ('Austria', 'Salzburg'): ('Austria', ''),
     ('Austria', 'Wien'): ('Austria', ''),
     ('Austria', ''): ('Austria', ''),
     ('Belgium', 'Forest'): ('Belgium', ''),
     ('Belgium', ''): ('Belgium', ''),
     ('België', 'Antwerpen'): ('Belgium', ''),
     ('Brazil', 'DF'): ('Brazil', 'DF'),
     ('Brazil', 'MG'): ('Brazil', 'MG'),
     ('Brazil', 'RJ'): ('Brazil', 'RJ'),
     ('Brazil', 'RN'): ('Brazil', 'RN'),
     ('Brazil', 'Rio de Janeiro'): ('Brazil', 'RJ'),
     ('Brazil', 'SP'): ('Brazil', 'SP'),
     ('CANADA', 'BC'): ('Canada', 'BC'),
     ('Canada', 'AB'): ('Canada', 'AB'),
     ('Canada', 'BC'): ('Canada', 'BC'),
     ('Canada', 'MB'): ('Canada', 'MB'),
     ('Canada', 'NB'): ('Canada', 'NB'),
     ('Canada', 'NL'): ('Canada', 'NL'),
     ('Canada', 'NS'): ('Canada', 'NS'),
     ('Canada', 'ON'): ('Canada', 'ON'),
     ('Canada', 'Ontario'): ('Canada', 'ON'),
     ('Canada', 'PEI'): ('Canada', 'PE'),
     ('Canada', 'QC'): ('Canada', 'QC'),
     ('Canada', 'Québec'): ('Canada', 'QC'),
     ('Canada', 'SK'): ('Canada', 'SK'),
     ('Colombia', 'Antioquia'): ('Colombia', ''),
     ('Colombia', 'DC'): ('Colombia', ''),
     ('Czech Republic', ''): ('Czechia', ''),
     ('Denmark', 'Copenhagen'): ('Denmark', ''),
     ('Deutschland', 'BRD'): ('Germany', ''),
     ('Deutschland', 'Baden Wuertemberg'): ('Germany', ''),
     ('Deutschland', 'Baden-Würtemberg'): ('Germany', ''),
     ('Deutschland', 'Bavaria'): ('Germany', ''),
     ('Deutschland', 'Deutschland'): ('Germany', ''),
     ('Deutschland', 'NRW'): ('Germany', ''),
     ('Ecuador', ''): ('Ecuador', ''),
     ('England', 'Greater London'): ('United Kingdom', ''),
     ('England', 'Oxford'): ('United Kingdom', ''),
     ('England', ''): ('United Kingdom', ''),
     ('Finland', '-'): ('Finland', ''),
     ('France', "Cote d'Or"): ('France', ''),
     ('France', 'Gironde'): ('France', ''),
     ('France', 'Ile de France'): ('France', ''),
     ('France', 'Ile-de-France'): ('France', ''),
     ('France', 'Lorraine'): ('France', ''),
     ('France', 'Pays de la Loire'): ('France', ''),
     ('France', ''): ('France', ''),
     ('France', 'Île de France'): ('France', ''),
     ('GREAT BRITAIN', 'Somerset'): ('United Kingdom', ''),
     ('Germany', '-'): ('Germany', ''),
     ('Germany', '.'): ('Germany', ''),
     ('Germany', 'BRD'): ('Germany', ''),
     ('Germany', 'BW'): ('Germany', ''),
     ('Germany', 'Baden Wuertemberg'): ('Germany', ''),
     ('Germany', 'Baden-Würtemberg'): ('Germany', ''),
     ('Germany', 'Bavaria'): ('Germany', ''),
     ('Germany', 'Bayern'): ('Germany', ''),
     ('Germany', 'Berlin'): ('Germany', ''),
     ('Germany', 'Bremen'): ('Germany', ''),
     ('Germany', 'Germany'): ('Germany', ''),
     ('Germany', 'Hamburg'): ('Germany', ''),
     ('Germany', 'Hessen'): ('Germany', ''),
     ('Germany', 'NRW'): ('Germany', ''),
     ('Germany', ''): ('Germany', ''),
     ('Greece', 'Rodopi'): ('Greece', ''),
     ('Hungary', ''): ('Hungary', ''),
     ('Ireland', 'Dublin'): ('Ireland', ''),
     ('Ireland', ''): ('Ireland', ''),
     ('Israel', ''): ('Israel', ''),
     ('Italia', 'FI'): ('Italy', 'FI'),
     ('Italia', 'Torino'): ('Italy', 'TO'),
     ('Italy', 'BS'): ('Italy', 'BS'),
     ('Italy', 'IT'): ('Italy', 'VT'),
     ('Italy', 'Milano'): ('Italy', 'MI'),
     ('Italy', 'Rome'): ('Italy', 'RM'),
     ('Italy', ''): ('Italy', ''),
     ('Japan', 'Aichi'): ('Japan', '23'),
     ('Japan', 'Kan'): ('Japan', ''),
     ('Japan', 'Kanagawa'): ('Japan', '14'),
     ('Japan', 'Saitama'): ('Japan', '11'),
     ('Japan', 'Shiga'): ('Japan', '25'),
     ('Japan', 'Tokyo'): ('Japan', '13'),
     ('Japan', ''): ('Japan', ''),
     ('MEXICO', 'Ciudad de México'): ('Mexico', 'CMX'),
     ('', 'AE'): ('United States', 'AE'),
     ('', 'AK'): ('United States', 'AK'),
     ('', 'AL'): ('United States', 'AL'),
     ('', 'AR'): ('United States', 'AR'),
     ('', 'AZ'): ('United States', 'AZ'),
     ('', 'CA'): ('United States', 'CA'),
     ('', 'CO'): ('United States', 'CO'),
     ('', 'CT'): ('United States', 'CT'),
     ('', 'DC'): ('United States', 'DC'),
     ('', 'DE'): ('United States', 'DE'),
     ('', 'FL'): ('United States', 'FL'),
     ('', 'Florida'): ('United States', 'FL'),
     ('', 'GA'): ('United States', 'GA'),
     ('', 'HI'): ('United States', 'HI'),
     ('', 'IA'): ('United States', 'IA'),
     ('', 'ID'): ('United States', 'ID'),
     ('', 'IL'): ('United States', 'IL'),
     ('', 'IN'): ('United States', 'IN'),
     ('', 'KS'): ('United States', 'KS'),
     ('', 'KY'): ('United States', 'KY'),
     ('', 'LA'): ('United States', 'LA'),
     ('', 'MA'): ('United States', 'MA'),
     ('', 'MD'): ('United States', 'MD'),
     ('', 'ME'): ('United States', 'ME'),
     ('', 'MI'): ('United States', 'MI'),
     ('', 'MN'): ('United States', 'MN'),
     ('', 'MO'): ('United States', 'MO'),
     ('', 'MS'): ('United States', 'MS'),
     ('', 'MT'): ('United States', 'MT'),
     ('', 'NC'): ('United States', 'NC'),
     ('', 'NE'): ('United States', 'NE'),
     ('', 'NH'): ('United States', 'NH'),
     ('', 'NJ'): ('United States', 'NJ'),
     ('', 'NM'): ('United States', 'NM'),
     ('', 'NV'): ('United States', 'NV'),
     ('', 'NY'): ('United States', 'NY'),
     ('', 'OH'): ('United States', 'OH'),
     ('', 'OK'): ('United States', 'OK'),
     ('', 'OR'): ('United States', 'OR'),
     ('', 'Ohio'): ('United States', 'OH'),
     ('', 'PA'): ('United States', 'PA'),
     ('', 'PR'): ('United States', 'PR'),
     ('', 'RI'): ('United States', 'RI'),
     ('', 'SC'): ('United States', 'SC'),
     ('', 'TN'): ('United States', 'TN'),
     ('', 'TX'): ('United States', 'TX'),
     ('', 'UT'): ('United States', 'UT'),
     ('', 'VA'): ('United States', 'VA'),
     ('', 'VT'): ('United States', 'VT'),
     ('', 'WA'): ('United States', 'WA'),
     ('', 'WI'): ('United States', 'WI'),
     ('', 'WV'): ('United States', 'WV'),
     ('', 'WY'): ('United States', 'WY'),
     ('Mexico', 'Mexico City'): ('Mexico', 'CMX'),
     ('Mexico', 'QR'): ('Mexico', 'QR'),
     ('Mexico', 'Quintana Roo'): ('Mexico', 'ROO'),
     ('Mexico', 'Sonora'): ('Mexico', 'SON'),
     ('Mexico', 'Veracruz'): ('Mexico', 'VER'),
     ('Mexico', 'Yucatan'): ('Mexico', 'YUC'),
     ('México', 'Jalisco'): ('Mexico', 'JAL'),
     ('Netherlands', 'Noord Holland'): ('Netherlands', ''),
     ('Netherlands', 'Z.H.'): ('Netherlands', ''),
     ('Netherlands', 'Zuid-Holland'): ('Netherlands', ''),
     ('Netherlands', ''): ('Netherlands', ''),
     ('New Zealand', 'Auckland'): ('New Zealand', 'AUK'),
     ('New Zealand', 'Wellington'): ('New Zealand', 'WGN'),
     ('New Zealand', '_'): ('New Zealand', ''),
     ('New Zealand', ''): ('New Zealand', ''),
     ('Niederlande', 'OV'): ('Netherlands', ''),
     ('Norway', 'Norway (NOR)'): ('Norway', ''),
     ('Norway', 'Vestland'): ('Norway', ''),
     ('Peru', 'Lima'): ('Peru', ''),
     ('Poland', 'Malopolskie'): ('Poland', ''),
     ('Poland', ''): ('Poland', ''),
     ('Singapore', '.'): ('Singapore', ''),
     ('Singapore', 'Singapore'): ('Singapore', ''),
     ('South Africa', 'Western Cape'): ('South Africa', ''),
     ('South Korea', ''): ('Korea, Republic of', ''),
     ('Spain', 'Catalunya'): ('Spain', ''),
     ('Spain', 'Toledo'): ('Spain', ''),
     ('Spain', ''): ('Spain', ''),
     ('Sweden', '.'): ('Sweden', ''),
     ('Sweden', 'Stockholm'): ('Sweden', ''),
     ('Sweden', 'Sweden'): ('Sweden', ''),
     ('Sweden', ''): ('Sweden', ''),
     ('Switzerland', '-'): ('Switzerland', ''),
     ('Switzerland', 'AG'): ('Switzerland', ''),
     ('Switzerland', 'BS'): ('Switzerland', ''),
     ('Switzerland', 'Ticino'): ('Switzerland', ''),
     ('Switzerland', 'Winterthur'): ('Switzerland', ''),
     ('Switzerland', 'Zürich'): ('Switzerland', ''),
     ('Switzerland', ''): ('Switzerland', ''),
     ('Taiwan', 'Taiwan'): ('Taiwan', ''),
     ('The Netherlands', ''): ('Netherlands', ''),
     ('U.K.', 'Gloucestershire'): ('United Kingdom', ''),
     ('UK', 'Dorset'): ('United Kingdom', ''),
     ('UK', 'Hants'): ('United Kingdom', ''),
     ('UK', 'London'): ('United Kingdom', ''),
     ('UK', 'Middx'): ('United Kingdom', ''),
     ('UK', 'North Yorkshire'): ('United Kingdom', ''),
     ('UK', 'Oxfordshire'): ('United Kingdom', ''),
     ('UK', 'Sussex'): ('United Kingdom', ''),
     ('UK', ''): ('United Kingdom', ''),
     ('US', 'IA'): ('United States', 'IA'),
     ('US', 'IN'): ('United States', 'IN'),
     ('US', 'KY'): ('United States', 'KY'),
     ('US', 'MA'): ('United States', 'MA'),
     ('US', 'MD'): ('United States', 'MD'),
     ('US', 'MI'): ('United States', 'MI'),
     ('US', 'MN'): ('United States', 'MN'),
     ('US', 'NC'): ('United States', 'NC'),
     ('US', 'NV'): ('United States', 'NV'),
     ('US', 'NY'): ('United States', 'NY'),
     ('USA', 'AL'): ('United States', 'AL'),
     ('USA', 'AR'): ('United States', 'AR'),
     ('USA', 'AZ'): ('United States', 'AZ'),
     ('USA', 'CA'): ('United States', 'CA'),
     ('USA', 'CO'): ('United States', 'CO'),
     ('USA', 'CT'): ('United States', 'CT'),
     ('USA', 'Ca'): ('United States', 'CA'),
     ('USA', 'DC'): ('United States', 'DC'),
     ('USA', 'DE'): ('United States', 'DE'),
     ('USA', 'FL'): ('United States', 'FL'),
     ('USA', 'GA'): ('United States', 'GA'),
     ('USA', 'HI'): ('United States', 'HI'),
     ('USA', 'IA'): ('United States', 'IA'),
     ('USA', 'ID'): ('United States', 'ID'),
     ('USA', 'IL'): ('United States', 'IL'),
     ('USA', 'IN'): ('United States', 'IN'),
     ('USA', 'KS'): ('United States', 'KS'),
     ('USA', 'KY'): ('United States', 'KY'),
     ('USA', 'LA'): ('United States', 'LA'),
     ('USA', 'MA'): ('United States', 'MA'),
     ('USA', 'MD'): ('United States', 'MD'),
     ('USA', 'ME'): ('United States', 'ME'),
     ('USA', 'MI'): ('United States', 'MI'),
     ('USA', 'MN'): ('United States', 'MN'),
     ('USA', 'MO'): ('United States', 'MO'),
     ('USA', 'MS'): ('United States', 'MS'),
     ('USA', 'MT'): ('United States', 'MT'),
     ('USA', 'NC'): ('United States', 'NC'),
     ('USA', 'ND'): ('United States', 'ND'),
     ('USA', 'NE'): ('United States', 'NE'),
     ('USA', 'NH'): ('United States', 'NH'),
     ('USA', 'NJ'): ('United States', 'NJ'),
     ('USA', 'NM'): ('United States', 'NM'),
     ('USA', 'NV'): ('United States', 'NV'),
     ('USA', 'NY'): ('United States', 'NY'),
     ('USA', 'OH'): ('United States', 'OH'),
     ('USA', 'OK'): ('United States', 'OK'),
     ('USA', 'OR'): ('United States', 'OR'),
     ('USA', 'PA'): ('United States', 'PA'),
     ('USA', 'PR'): ('United States', 'PR'),
     ('USA', 'RI'): ('United States', 'RI'),
     ('USA', 'SC'): ('United States', 'SC'),
     ('USA', 'SD'): ('United States', 'SD'),
     ('USA', 'TN'): ('United States', 'TN'),
     ('USA', 'TX'): ('United States', 'TX'),
     ('USA', 'UT'): ('United States', 'UT'),
     ('USA', 'VA'): ('United States', 'VA'),
     ('USA', 'VT'): ('United States', 'VT'),
     ('USA', 'Va'): ('United States', 'VA'),
     ('USA', 'WA'): ('United States', 'WA'),
     ('USA', 'WI'): ('United States', 'WI'),
     ('USA', 'WV'): ('United States', 'WV'),
     ('USA', 'WY'): ('United States', 'WY'),
     ('United Kingdom', 'Cheshire'): ('United Kingdom', ''),
     ('United Kingdom', 'Devon'): ('United Kingdom', ''),
     ('United Kingdom', 'Durham'): ('United Kingdom', ''),
     ('United Kingdom', 'Gwynedd'): ('United Kingdom', ''),
     ('United Kingdom', 'Kent'): ('United Kingdom', ''),
     ('United Kingdom', 'Lanarkshire'): ('United Kingdom', ''),
     ('United Kingdom', 'London'): ('United Kingdom', ''),
     ('United Kingdom', 'Norfolk'): ('United Kingdom', ''),
     ('United Kingdom', 'Oxfordshire'): ('United Kingdom', ''),
     ('United Kingdom', 'Scotland'): ('United Kingdom', ''),
     ('United Kingdom', 'Shropshire'): ('United Kingdom', ''),
     ('United Kingdom', 'Stockport'): ('United Kingdom', ''),
     ('United Kingdom', 'Suffolk'): ('United Kingdom', ''),
     ('United Kingdom', 'Tyne and Wear'): ('United Kingdom', ''),
     ('United Kingdom', 'Wales'): ('United Kingdom', ''),
     ('United Kingdom', 'West Sussex'): ('United Kingdom', ''),
     ('United Kingdom', 'West Yorkshire'): ('United Kingdom', ''),
     ('United Kingdom', ''): ('United Kingdom', ''),
     ('United States', 'CA'): ('United States', 'CA'),
     ('United States', 'CO'): ('United States', 'CO'),
     ('United States', 'CT'): ('United States', 'CT'),
     ('United States', 'DC'): ('United States', 'DC'),
     ('United States', 'DE'): ('United States', 'DE'),
     ('United States', 'FL'): ('United States', 'FL'),
     ('United States', 'GA'): ('United States', 'GA'),
     ('United States', 'IN'): ('United States', 'IN'),
     ('United States', 'KS'): ('United States', 'KS'),
     ('United States', 'LA'): ('United States', 'LA'),
     ('United States', 'MA'): ('United States', 'MA'),
     ('United States', 'MD'): ('United States', 'MD'),
     ('United States', 'ME'): ('United States', 'ME'),
     ('United States', 'MI'): ('United States', 'MI'),
     ('United States', 'MN'): ('United States', 'MN'),
     ('United States', 'NC'): ('United States', 'NC'),
     ('United States', 'NJ'): ('United States', 'NJ'),
     ('United States', 'NM'): ('United States', 'NM'),
     ('United States', 'NY'): ('United States', 'NY'),
     ('United States', 'OH'): ('United States', 'OH'),
     ('United States', 'OR'): ('United States', 'OR'),
     ('United States', 'Oregon'): ('United States', 'OR'),
     ('United States', 'PA'): ('United States', 'PA'),
     ('United States', 'TN'): ('United States', 'TN'),
     ('United States', 'TX'): ('United States', 'TX'),
     ('United States', 'UT'): ('United States', 'UT'),
     ('United States', 'VA'): ('United States', 'VA'),
     ('United States', 'WA'): ('United States', 'WA'),
     ('United States', 'WI'): ('United States', 'WI'),
     ('', 'AL'): ('United States', 'AL'),
     ('', 'AZ'): ('United States', 'AZ'),
     ('', 'CA'): ('United States', 'CA'),
     ('', 'CT'): ('United States', 'CT'),
     ('', 'DC'): ('United States', 'DC'),
     ('', 'GA'): ('United States', 'GA'),
     ('', 'HI'): ('United States', 'HI'),
     ('', 'IL'): ('United States', 'IL'),
     ('', 'IN'): ('United States', 'IN'),
     ('', 'KY'): ('United States', 'KY'),
     ('', 'MA'): ('United States', 'MA'),
     ('', 'MD'): ('United States', 'MD'),
     ('', 'MI'): ('United States', 'MI'),
     ('', 'MN'): ('United States', 'MN'),
     ('', 'MO'): ('United States', 'MO'),
     ('', 'MS'): ('United States', 'MS'),
     ('', 'NC'): ('United States', 'NC'),
     ('', 'NH'): ('United States', 'NH'),
     ('', 'NJ'): ('United States', 'NJ'),
     ('', 'NY'): ('United States', 'NY'),
     ('', 'OH'): ('United States', 'OH'),
     ('', 'SD'): ('United States', 'SD'),
     ('', 'TN'): ('United States', 'TN'),
     ('', 'TX'): ('United States', 'TX'),
     ('', 'UT'): ('United States', 'UT'),
     ('', 'VA'): ('United States', 'VA'),
    #  ('', ''): ('', ''),
     ('usa', 'CA'): ('United States', 'CA'),
     ('usa', 'NM'): ('United States', 'NM'),
     ('usa', 'WA'): ('United States', 'WA'),
     ('日本 (Japan)', 'Ibaraki'): ('Japan', '08')
 }

with transaction.atomic():
    clean_countries()
