# Generated by Django 3.1.2 on 2020-10-02 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMembershipSubscriptionPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('stripe_payment_intent_id', models.TextField(help_text='The PaymentIntent ID for the stripe checkout session for this purchase.')),
                ('is_completed', models.BooleanField(blank=True, help_text='Indicates whether payment has succeeded and the subscription has been purchased.')),
                ('user', models.ForeignKey(help_text='The user to purchase a subscription for.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
