# Generated by Django 3.1.2 on 2020-10-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingmembershipsubscriptionpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('membership_secretary', 'Membership Secretary'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
