# Generated by Django 3.1.3 on 2020-11-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0006_user_profile_fields'), ('accounts', '0007_user_profile_changes'), ('accounts', '0008_directory_choices_fix'), ('accounts', '0009_user_profile_checkboxes')]

    dependencies = [
        ('accounts', '0005_auto_20201112_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='do_not_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_remote_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_young_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address_country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='educational_institution_affiliation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='include_address_in_conclave_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_address_in_mailing_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_address_in_membership_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_email_in_conclave_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_email_in_mailing_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_email_in_membership_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_name_in_conclave_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_name_in_mailing_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_name_in_membership_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_phone_in_conclave_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_phone_in_mailing_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='include_phone_in_membership_directory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_builder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='other_commercial',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
