# Generated by Django 3.1.4 on 2021-01-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210109_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipsubscription',
            name='membership_type',
            field=models.CharField(choices=[('regular', 'Regular ($35)'), ('student', 'Student ($20)'), ('international', 'International ($40)'), ('lifetime', 'Lifetime')], max_length=50),
        ),
        migrations.AlterField(
            model_name='membershipsubscriptionhistory',
            name='membership_type',
            field=models.CharField(choices=[('regular', 'Regular ($35)'), ('student', 'Student ($20)'), ('international', 'International ($40)'), ('lifetime', 'Lifetime')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingmembershipsubscriptionpurchase',
            name='membership_type',
            field=models.CharField(choices=[('regular', 'Regular ($35)'), ('student', 'Student ($20)'), ('international', 'International ($40)'), ('lifetime', 'Lifetime')], max_length=50),
        ),
    ]
