# Generated by Django 3.1.4 on 2021-01-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210115_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('membership_secretary', 'Membership Secretary'), ('board_member', 'Board Member'))},
        ),
    ]
