# Generated by Django 3.2.13 on 2023-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_accountpermissions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receives_expiration_reminder_emails',
            field=models.BooleanField(default=True),
        ),
    ]
