# Generated by Django 3.1.3 on 2020-11-19 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_profile_checkboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsubscription',
            name='years_renewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
