# Generated by Django 3.1.4 on 2021-01-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_membershipsubscription_years_renewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='include_address_in_conclave_directory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='include_email_in_conclave_directory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='include_name_in_conclave_directory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='include_phone_in_conclave_directory',
        ),
    ]
