# Generated by Django 3.1.4 on 2021-01-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210108_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
