# Generated by Django 3.1.4 on 2021-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210108_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
