# Generated by Django 3.1.4 on 2021-01-19 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210118_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeemailrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershipsubscription',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingmembershipsubscriptionpurchase',
            name='user',
            field=models.ForeignKey(help_text='The user to purchase a subscription for.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_is_family_member_for',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='accounts.membershipsubscription'),
        ),
        migrations.DeleteModel(
            name='MembershipSubscriptionHistory',
        ),
    ]
