# Generated by Django 3.1.4 on 2021-02-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210129_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commercial_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
