# Generated by Django 3.1.4 on 2021-02-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210205_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='include_address_in_mailing_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='include_email_in_mailing_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='include_name_in_mailing_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='include_phone_in_mailing_list',
        ),
    ]
