# Generated by Django 3.1.5 on 2021-02-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210211_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('membership_secretary', 'Membership Secretary'), ('board_member', 'Board Member'), ('rental_manager', 'Rental Manager'))},
        ),
    ]
