# Generated by Django 3.2.23 on 2023-12-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_receives_expiration_reminder_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipsubscription',
            name='membership_type',
            field=models.CharField(choices=[('regular', 'Regular ($40)'), ('student', 'Student ($20)'), ('international', 'International ($45)'), ('lifetime', 'Lifetime'), ('complementary', 'Complementary'), ('organization', 'Organization')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingmembershipsubscriptionpurchase',
            name='membership_type',
            field=models.CharField(choices=[('regular', 'Regular ($40)'), ('student', 'Student ($20)'), ('international', 'International ($45)'), ('lifetime', 'Lifetime'), ('complementary', 'Complementary'), ('organization', 'Organization')], max_length=50),
        ),
    ]
