# Generated by Django 3.1.7 on 2021-10-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0012_instrumentbringing_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentbringing',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
