# Generated by Django 3.1.7 on 2021-10-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0018_auto_20211013_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='include_in_whos_coming_to_conclave_list',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes'),
            preserve_default=False,
        ),
    ]
