# Generated by Django 3.2.9 on 2022-01-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0020_flex_class_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularprogramclasschoices',
            name='wants_extra_beginner_class',
            field=models.TextField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
        ),
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular Curriculum'), ('part_time', 'Part-Time Curriculum (1 class + optional freebie)'), ('beginners', 'Introduction to the Viol (free)'), ('consort_coop', 'Consort Cooperative'), ('seasoned_players', 'Seasoned Players'), ('advanced_projects', 'Advanced Projects'), ('faculty_guest_other', 'Faculty')], max_length=50),
        ),
    ]
