# Generated by Django 3.2.9 on 2022-01-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0022_housing'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='additional_housing_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='housing',
            name='arrival_day',
            field=models.TextField(choices=[('fixme1', 'FIXME2')]),
        ),
        migrations.AlterField(
            model_name='housing',
            name='departure_day',
            field=models.TextField(choices=[('fixme1', 'FIXME2')]),
        ),
        migrations.AlterField(
            model_name='housing',
            name='normal_bed_time',
            field=models.TextField(choices=[('no_preference', 'No Preference'), ('early', 'Early to bed (11pm)'), ('late', 'Late night (could be 2am!)')], default='no_preference'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='room_type',
            field=models.TextField(choices=[('single', 'Single'), ('double', 'Double'), ('off_campus', 'Off Campus')], default=''),
        ),
    ]
