# Generated by Django 3.2.11 on 2022-03-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0032_rename_intro_to_viol_extra_class_fee_conclaveregistrationconfig_beginners_extra_class_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='seasoned_players_extra_class_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
