# Generated by Django 3.2.11 on 2022-03-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0034_conclaveregistrationconfig_work_study_scholarship_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='canadian_discount_percent',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='housing_subsidy_amount',
            field=models.IntegerField(blank=True, default=150),
        ),
    ]
