# Generated by Django 3.2.11 on 2022-03-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0039_advanced_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularprogramclasschoices',
            name='wants_extra_beginner_class',
        ),
    ]
