# Generated by Django 3.2.11 on 2022-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0040_remove_regularprogramclasschoices_wants_extra_beginner_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='offer_to_beginners',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
