# Generated by Django 3.2.11 on 2022-03-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0042_additionalregistrationinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='gender',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Other', 'Other')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='pronouns',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
