# Generated by Django 3.2.11 on 2022-03-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0046_remove_conclaveregistrationconfig_work_study_scholarship_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstudyapplication',
            old_name='nickname_and_pronouns',
            new_name='nickname',
        ),
    ]
