# Generated by Django 3.2.11 on 2022-03-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0047_rename_nickname_and_pronouns_workstudyapplication_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstudyapplication',
            name='has_been_to_conclave',
            field=models.TextField(choices=[('yes', 'Yes, in person'), ('online', 'Yes, online only'), ('no', 'No')]),
        ),
    ]
