# Generated by Django 3.2.11 on 2022-03-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0048_alter_workstudyapplication_has_been_to_conclave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstudyapplication',
            name='has_been_to_conclave',
            field=models.TextField(choices=[('yes', 'Yes, in person'), ('online', 'Yes, online only'), ('both', 'Yes, in person and online'), ('no', 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='workstudyapplication',
            name='has_done_work_study',
            field=models.TextField(choices=[('yes', 'Yes, in person'), ('online', 'Yes, online only'), ('no', 'No')], default=''),
        ),
    ]
