# Generated by Django 3.2.11 on 2022-03-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0050_auto_20220328_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstudyapplication',
            name='can_stay_until_sunday_afternoon',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], default='no'),
            preserve_default=False,
        ),
    ]
