# Generated by Django 3.2.11 on 2022-03-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0054_workstudyapplication_has_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstudyapplication',
            name='early_arrival',
            field=models.CharField(choices=[('friday_evening', 'Yes, I would like to come early, and can arrive on Friday before 6pm'), ('saturday_morning', 'Yes, I would like to come early, and can arrive on Saturday before noon'), ('saturday_evening', 'Yes, I would like to come early, and can arrive on Saturday before 6pm'), ('no', 'No, I do not want to come early, and will plan to arrive on Sunday')], max_length=100),
        ),
    ]
