# Generated by Django 3.2.11 on 2022-03-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0056_alter_workstudyapplication_early_arrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalregistrationinfo',
            name='archival_video_release',
        ),
        migrations.RemoveField(
            model_name='conclaveregistrationconfig',
            name='archival_video_release_text',
        ),
    ]
