# Generated by Django 3.2.11 on 2022-03-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0057_auto_20220328_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='landing_page_markdown',
            field=models.TextField(blank=True),
        ),
    ]
