# Generated by Django 3.2.11 on 2022-03-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0058_conclaveregistrationconfig_landing_page_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='covid_policy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular Curriculum Full-time (2-3 classes + optional "Freebie")'), ('part_time', 'Regular Curriculum Part-time (1 class only)'), ('beginners', 'Beginning Viol (tuition free)'), ('consort_coop', 'Consort Co-op (CC 3+1 or CC 2+2)'), ('seasoned_players', 'Seasoned Players'), ('advanced_projects', 'Advanced Projects'), ('faculty_guest_other', 'Faculty'), ('non_playing_attendee', 'Non-playing Attendee')], max_length=50),
        ),
    ]
