# Generated by Django 3.2.11 on 2022-04-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0061_alter_class_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conclaveregistrationconfig',
            old_name='non_playing_attendee_fee',
            new_name='workshop_fee',
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='beginners_two_extra_classes_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='early_arrival_date_options',
            field=models.TextField(blank=True),
        ),
    ]
