# Generated by Django 3.2.11 on 2022-04-17 15:41

from django.db import migrations, models
import vdgsa_backend.conclave_registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0062_auto_20220417_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclaveregistrationconfig',
            name='arrival_date_options',
            field=models.TextField(blank=True, validators=[vdgsa_backend.conclave_registration.models._arrival_and_departure_date_options_validator]),
        ),
        migrations.AlterField(
            model_name='conclaveregistrationconfig',
            name='departure_date_options',
            field=models.TextField(blank=True, validators=[vdgsa_backend.conclave_registration.models._arrival_and_departure_date_options_validator]),
        ),
        migrations.AlterField(
            model_name='conclaveregistrationconfig',
            name='early_arrival_date_options',
            field=models.TextField(blank=True, validators=[vdgsa_backend.conclave_registration.models._arrival_and_departure_date_options_validator]),
        ),
    ]
