# Generated by Django 3.2.11 on 2022-04-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0065_auto_20220417_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='dietary_needs_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registrationentry',
            name='program',
            field=models.CharField(choices=[('regular', 'Regular Curriculum Full-time (2-3 classes + optional "Freebie")'), ('part_time', 'Regular Curriculum Part-time (1 class only)'), ('beginners', 'Beginning Viol (free to local attendees)'), ('consort_coop', 'Consort Co-op (CC 3+1 or CC 2+2)'), ('seasoned_players', 'Seasoned Players'), ('advanced_projects', 'Advanced Projects'), ('faculty_guest_other', 'Faculty'), ('non_playing_attendee', 'Non-playing Attendee')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workstudyapplication',
            name='has_done_work_study',
            field=models.TextField(choices=[('yes', 'Yes, in person'), ('online', 'Yes, online only'), ('both', 'Yes, in person and online'), ('no', 'No')], default=''),
        ),
    ]
