# Generated by Django 3.2.11 on 2022-04-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0066_auto_20220417_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='num_display_space_days',
            field=models.IntegerField(default=0),
        ),
    ]
