# Generated by Django 3.2.11 on 2022-04-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0067_additionalregistrationinfo_num_display_space_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='vendor_table_per_day_cost',
            field=models.IntegerField(blank=True, default=25),
        ),
    ]
