# Generated by Django 3.2.11 on 2022-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0072_additionalregistrationinfo_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='instruments_page_markdown',
            field=models.TextField(blank=True),
        ),
    ]
