# Generated by Django 3.2.13 on 2023-03-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0074_auto_20230327_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstudyapplication',
            name='has_been_to_conclave',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='workstudyapplication',
            name='has_done_work_study',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], default=''),
        ),
    ]
