# Generated by Django 3.2.11 on 2023-04-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0076_alter_registrationentry_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='supplemental_2023_housing_subsidy_amount',
            field=models.IntegerField(blank=True, default=225),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='trust_discount_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='wants_2023_supplemental_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='housing',
            name='room_type',
            field=models.TextField(choices=[('single', 'Single'), ('double', 'Double (sharing a bed)'), ('off_campus', 'Off Campus')], default=''),
        ),
    ]
