# Generated by Django 3.2.11 on 2023-04-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0078_rename_trust_discount_markdown_conclaveregistrationconfig_discount_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='roommate_preference_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='suitemate_preference_text',
            field=models.TextField(blank=True),
        ),
    ]
