# Generated by Django 3.2.11 on 2023-04-12 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0081_conclaveregistrationconfig_canadian_discount_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalregistrationinfo',
            name='num_display_space_days',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
