# Generated by Django 3.2.11 on 2023-04-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0083_conclaveregistrationconfig_confirmation_email_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclaveregistrationconfig',
            name='confirmation_email_intro_text',
            field=models.TextField(blank=True, default='This text is customizable. If you want a blank line, put only <br> on that line. Other blank lines will be removed.'),
        ),
    ]
