# Generated by Django 3.2.19 on 2024-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0084_alter_conclaveregistrationconfig_confirmation_email_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='charge_card_date_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='code_of_conduct_markdown',
            field=models.TextField(blank=True),
        ),
    ]
