# Generated by Django 3.2.19 on 2024-04-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0088_alter_housing_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='prorated_workshop_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
