# Generated by Django 3.2.25 on 2025-02-28 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0092_auto_20250227_2148'),
        ('conclave_registration', '0092_is_freebie'),
    ]

    operations = [
    ]
