# Generated by Django 3.2.25 on 2025-12-30 16:29

from django.db import migrations, models
import django_resized.forms
import vdgsa_backend.conclave_registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0093_merge_0092_auto_20250227_2148_0092_is_freebie'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='user_image_file_name',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=-1, scale=None, size=[500, None], upload_to=vdgsa_backend.conclave_registration.models.AdditionalRegistrationInfo._user_image_file_folder),
        ),
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='user_image_opt_out',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='user_image_file_name_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='additionalregistrationinfo',
            name='age',
            field=models.TextField(choices=[('18-35', '18-35'), ('36-64', '36-64'), ('65+', '65+'), ('Under 18', 'Under 18 (Parent or Legal Guardian must also register)')]),
        ),
        migrations.AlterField(
            model_name='beginnerinstrumentinfo',
            name='instrument_bringing',
            field=models.TextField(blank=True, choices=[('treble', 'Treble'), ('tenor', 'Tenor'), ('bass', '6-string Bass'), ('bass_7_string', '7-string Bass'), ('vielle', 'Vielle')]),
        ),
        migrations.AlterField(
            model_name='instrumentbringing',
            name='purpose',
            field=models.CharField(choices=[('bringing_for_self', "I'm bringing this instrument for myself"), ('willing_to_loan', "I'm willing to loan this instrument to someone else"), ('wants_to_borrow', 'I need to borrow this instrument'), ('could_play', 'I can play this instrument in class if one is provided')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instrumentbringing',
            name='size',
            field=models.CharField(choices=[('treble', 'Treble'), ('tenor', 'Tenor'), ('bass', '6-string Bass'), ('bass_7_string', '7-string Bass'), ('vielle', 'Vielle'), ('other', 'Other Instrument or Renaissance Viol')], max_length=100),
        ),
    ]
