# Generated by Django 3.2.25 on 2026-01-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0094_auto_20251230_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalregistrationinfo',
            name='attended_conclave_before',
            field=models.TextField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')]),
        ),
        migrations.AlterField(
            model_name='additionalregistrationinfo',
            name='include_in_whos_coming_to_conclave_list',
            field=models.TextField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')]),
        ),
    ]
