# Generated by Django 3.2.25 on 2026-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0095_auto_20260108_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
