# Generated by Django 3.2.25 on 2026-03-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0096_auto_20260111_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='newbie_how_long_playing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='newbie_other_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='newbie_play_regularly',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='newbie_repertoire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='additionalregistrationinfo',
            name='newbie_taken_lessons',
            field=models.TextField(blank=True),
        ),
    ]
