# Generated by Django 3.2.25 on 2026-03-13 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conclave_registration', '0097_auto_20260306_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='class_selection_text',
            field=models.TextField(blank=True, default='class_selection_text'),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='newbie_welcome_text',
            field=models.TextField(blank=True, default='newbie_welcome_text'),
        ),
        migrations.AddField(
            model_name='conclaveregistrationconfig',
            name='work_study_explanatory_text',
            field=models.TextField(blank=True, default='work_study_explanatory_text'),
        ),
        migrations.AlterField(
            model_name='additionalregistrationinfo',
            name='can_drive_loaners',
            field=models.TextField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe'), ('N/A', 'N/A')]),
        ),
        migrations.AlterField(
            model_name='beginnerinstrumentinfo',
            name='instrument_bringing',
            field=models.TextField(blank=True, choices=[('treble', 'Treble'), ('tenor', 'Tenor'), ('bass', '6-string Bass'), ('bass_7_string', '7-string Bass'), ('renaissance_viol', 'Renaissance Viol'), ('vielle', 'Vielle')]),
        ),
        migrations.AlterField(
            model_name='housing',
            name='dietary_needs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('dairy_free', 'Dairy Free'), ('gluten_free', 'Gluten Free'), ('nut_allergy', 'Nut Allergy'), ('shellfish_allergy', 'Shellfish Allergy'), ('no_restrictions', 'No Restrictions')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='instrumentbringing',
            name='size',
            field=models.CharField(choices=[('treble', 'Treble'), ('tenor', 'Tenor'), ('bass', '6-string Bass'), ('bass_7_string', '7-string Bass'), ('renaissance_viol', 'Renaissance Viol'), ('vielle', 'Vielle'), ('other', 'Other Instrument (specify below)')], max_length=100),
        ),
    ]
